"""Build a minimal, deterministic, legally clean synthetic torrent corpus.

Every payload byte, file name, and tracker URL below is generated by
this module -- nothing is downloaded, nothing is a real public torrent,
and no path/username/hostname identifies a real person or machine.
Hashing is single-round SHA-1 over one 16 KiB piece via the in-house
`_bencode` encoder (BEP 0003); there is exactly one piece per file, so
no partial-piece edge case needs to be modeled.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path

from tests.integration._bencode import bencode

PIECE_LENGTH = 16384


@dataclass(frozen=True)
class SyntheticTorrent:
    """One generated synthetic torrent: its bytes, payload, and infohash."""

    name: str
    file_name: str
    payload: bytes
    torrent_bytes: bytes
    info_hash_hex: str


def _make_payload(label: bytes) -> bytes:
    """Return deterministic, repeatable filler content for one file.

    Content is derived from `label` alone (no randomness, no clock) so
    the same corpus -- and the same infohash -- is produced on every
    run and every machine.
    """
    filler = (b"qbit-ops synthetic test payload -- " + label + b" -- ") * 512
    return filler[:PIECE_LENGTH]


def _build_torrent(
    *,
    name: str,
    file_name: str,
    payload: bytes,
    announce: str | None,
) -> SyntheticTorrent:
    piece_sha1 = hashlib.sha1(payload, usedforsecurity=False).digest()
    info = {
        "name": file_name,
        "piece length": PIECE_LENGTH,
        "pieces": piece_sha1,
        "length": len(payload),
    }
    info_hash = hashlib.sha1(bencode(info), usedforsecurity=False)

    torrent: dict[str, object] = {
        "info": info,
        "created by": "qbit-ops test harness (deterministic, synthetic)",
        "creation date": 0,
    }
    if announce is not None:
        torrent["announce"] = announce

    return SyntheticTorrent(
        name=name,
        file_name=file_name,
        payload=payload,
        torrent_bytes=bencode(torrent),
        info_hash_hex=info_hash.hexdigest(),
    )


def build_complete_torrent(*, announce: str | None = None) -> SyntheticTorrent:
    """Build the torrent whose payload the harness always places on disk.

    Adding this torrent to a container that already has
    `payload` written at the expected save path, then triggering a
    recheck, deterministically produces a seeding/completed state.
    """
    payload = _make_payload(b"complete")
    return _build_torrent(
        name="qbit-ops-sample-complete",
        file_name="qbit-ops-sample-complete.bin",
        payload=payload,
        announce=announce,
    )


def build_incomplete_torrent(
    *, announce: str | None = None
) -> SyntheticTorrent:
    """Build the torrent whose payload the harness never writes to disk.

    A distinct payload (and therefore a distinct infohash) from
    `build_complete_torrent` -- the two can coexist in the same
    qBittorrent instance without a duplicate-torrent conflict.
    """
    payload = _make_payload(b"incomplete")
    return _build_torrent(
        name="qbit-ops-sample-incomplete",
        file_name="qbit-ops-sample-incomplete.bin",
        payload=payload,
        announce=announce,
    )


def build_tracked_torrent(*, announce: str) -> SyntheticTorrent:
    """Build the torrent used to exercise tracker add/remove/replace paths.

    `announce` must be a disposable, in-network-only tracker URL (see
    `tests/integration/_tracker_service.py`) -- never a real one.
    """
    payload = _make_payload(b"tracked")
    return _build_torrent(
        name="qbit-ops-sample-tracked",
        file_name="qbit-ops-sample-tracked.bin",
        payload=payload,
        announce=announce,
    )


def write_torrent_file(torrent: SyntheticTorrent, directory: Path) -> Path:
    """Write `torrent.torrent_bytes` to `directory/<name>.torrent`."""
    path = directory / f"{torrent.name}.torrent"
    path.write_bytes(torrent.torrent_bytes)
    return path


def write_payload_file(torrent: SyntheticTorrent, directory: Path) -> Path:
    """Write `torrent.payload` to `directory/<file_name>`, for a seeded add."""
    path = directory / torrent.file_name
    path.write_bytes(torrent.payload)
    return path
